apiVersion: v1
kind: Service
metadata:
  name: boilerplate-app
  namespace: fastapi-app
spec:
  type: LoadBalancer
  selector:
    app: boilerplate-app
  ports:
    - port: 8000
      targetPort: 8000
