apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fastapi-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # Headless (optional, or change to ClusterIP if needed)
